#Updated domain mappings
#Sun Feb 22 08:53:56 UTC 2026
norlund-johan-lukas.com=/home/lukas/users/norlund_johan_lukas_com
dev.norlund-johan-lukas.com=/home/lukas/UnityBuilds/NuggetsBuild/index.html
www.tekknat.com=/home/lukas/JavaServerProject/www
newdomain1.norlund-johan-lukas.com=/home/lukas/users/new_user1
ramen.norlund-johan-lukas.com=/home/lukas/users/ramen_norlund_johan_lukas_com
verify.norlund-johan-lukas.com=/home/lukas/users/verify_com
www.norlund-johan-lukas.com=/home/lukas/users/norlund_johan_lukas_com
fallback.tekknat.com=/home/lukas/users/fallback_tekknat_com
tekknat.com=/home/lukas/JavaServerProject/www
ludwig.norlund-johan-lukas.com=/home/lukas/UnityBuilds/BSCMM/index.html
