#Updated domain mappings
#Tue Jul 15 08:12:26 UTC 2025
norlund-johan-lukas.com=/home/lukas/JavaServerProject/www
dev.norlund-johan-lukas.com=/home/lukas/UnityBuilds/NuggetsBuild/index.html
newdomain1.norlund-johan-lukas.com=/home/lukas/users/new_user1
ramen.norlund-johan-lukas.com=/home/lukas/users/ramen_norlund_johan_lukas_com
verify.norlund-johan-lukas.com=/home/lukas/users/verify_com
www.norlund-johan-lukas.com=/home/lukas/JavaServerProject/www
ludwig.norlund-johan-lukas.com=/home/lukas/UnityBuilds/BSCMM/index.html
