#Updated PHP mappings
#Sun Feb 22 08:53:56 UTC 2026
norlund-johan-lukas.com=norlund_johan_lukas_com
ramen.norlund-johan-lukas.com=ramen_norlund_johan_lukas_com
verify.norlund-johan-lukas.com=verify_com
fallback.tekknat.com=fallback_tekknat_com
tekknat.com=tekknat_com
